manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/collin-grefer
  projects:
    - name: zmk
      remote: zmk
      revision: dracula-test
      import: app/west.yml
  self:
    path: config
